### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by nichamon** [nichamon/ovis#7]
- [ ] The top of OVIS-4 testing
  - [ ] Stage the zap_ugni pull requests and test them using the uGNI transport
- [ ] The event-driven patch https://github.com/ovis-hpc/ovis/pull/787
  - [ ]  https://github.com/nichamon/ovis/issues/4
- [ ] https://github.com/ovis-hpc/ovis/pull/777
  - [ ]  Ask Ann for example use cases so that we could write a test script in the `ldms-test` repo. Also, see the example provided in the pull request.
  - [ ] The format must be fixed before the patch gets merged.

**Comment by baallan** [comment]
- [ ] The commit 89ec911 needs to be updated. That version references hello stuff which has since been removed. It was updated by 4614eb304 in baallan:review_stream_csv_2 which uses ldmds_stream_publish and provides improved test case material.

**Comment by nichamon** [comment]
> * [ ]  The commit [89ec911](https://github.com/nichamon/ovis/commit/89ec911335fd92313b5c5b7cffe43c66b16779f1) needs to be updated. That version references hello stuff which has since been removed. It was updated by [4614eb3](https://github.com/nichamon/ovis/commit/4614eb304a8a40388427964a1c0687d2b316d0fd) in baallan:review_stream_csv_2 which uses ldmds_stream_publish and provides improved test case material.

@baallan Could you please add this to the PR in the ovis-hpc/ovis repo directly? This task list is my personal list. Thanks!
